#!/bin/bash
# setup_slurm.sh - Install & configure a single-node SLURM cluster on Ubuntu
# with Gmail-relayed email notifications (BEGIN / END / FAIL).
#
# Tested on: Ubuntu 22.04, slurm-wlm 21.08, cgroup v2 host, NVIDIA GPU.
# Requires: passwordless sudo (or run as root).
#
# Usage:
#   sudo ./setup_slurm.sh --email you@example.com --app-password "abcd efgh ijkl mnop" [options]
#
# Options:
#   --email ADDR           Gmail/Workspace address that sends AND receives (required)
#   --app-password PW      Google App Password (16 chars, spaces ok) (required)
#   --smtp-host HOST       SMTP relay host       (default: smtp.gmail.com)
#   --smtp-port PORT       SMTP relay port       (default: 587)
#   --smtp-user USER       SMTP auth user        (default: --email value)
#   --from ADDR            envelope From address (default: --email value)
#   --cluster NAME         ClusterName           (default: cluster)
#   --partition NAME       partition name        (default: main)
#   --no-test              skip the end-to-end test job + email
#   -h | --help            show this help
set -euo pipefail

# ---- defaults ----
EMAIL="" ; APP_PW="" ; SMTP_HOST="smtp.gmail.com" ; SMTP_PORT="587"
SMTP_USER="" ; FROM_ADDR="" ; CLUSTER="cluster" ; PARTITION="main" ; RUN_TEST=1

while [[ $# -gt 0 ]]; do
  case "$1" in
    --email)        EMAIL="$2"; shift 2 ;;
    --app-password) APP_PW="$2"; shift 2 ;;
    --smtp-host)    SMTP_HOST="$2"; shift 2 ;;
    --smtp-port)    SMTP_PORT="$2"; shift 2 ;;
    --smtp-user)    SMTP_USER="$2"; shift 2 ;;
    --from)         FROM_ADDR="$2"; shift 2 ;;
    --cluster)      CLUSTER="$2"; shift 2 ;;
    --partition)    PARTITION="$2"; shift 2 ;;
    --no-test)      RUN_TEST=0; shift ;;
    -h|--help)      grep '^#' "$0" | sed 's/^# \{0,1\}//' ; exit 0 ;;
    *) echo "Unknown arg: $1" >&2; exit 1 ;;
  esac
done

[[ -z "$EMAIL"  ]] && { echo "ERROR: --email is required" >&2; exit 1; }
[[ -z "$APP_PW" ]] && { echo "ERROR: --app-password is required" >&2; exit 1; }
[[ -z "$SMTP_USER" ]] && SMTP_USER="$EMAIL"
[[ -z "$FROM_ADDR" ]] && FROM_ADDR="$EMAIL"

# sudo shim (no-op if already root)
SUDO=""; [[ "$(id -u)" -ne 0 ]] && SUDO="sudo -n"

say() { printf '\n\033[1;36m==> %s\033[0m\n' "$*"; }

# ---- 1. packages ----
say "Installing packages (slurm-wlm, munge, msmtp, bsd-mailx)"
$SUDO apt-get update -qq
$SUDO env DEBIAN_FRONTEND=noninteractive apt-get install -y -qq \
  slurm-wlm slurmd slurmctld munge msmtp msmtp-mta bsd-mailx

# ---- 2. munge ----
say "Configuring munge"
if [[ ! -s /etc/munge/munge.key ]]; then
  $SUDO /usr/sbin/create-munge-key -f || true
fi
$SUDO systemctl enable --now munge
munge -n | unmunge | grep -q "STATUS:.*Success" && echo "munge OK" \
  || { echo "munge self-test FAILED" >&2; exit 1; }

# ---- 3. hardware detection ----
say "Detecting hardware"
HW=$($SUDO slurmd -C | head -1)          # NodeName=... CPUs=.. Boards=.. etc.
NODE=$(hostname -s)
CPUS=$(echo "$HW"    | grep -o 'CPUs=[0-9]*'            | cut -d= -f2)
SOCK=$(echo "$HW"    | grep -o 'SocketsPerBoard=[0-9]*' | cut -d= -f2)
CORES=$(echo "$HW"   | grep -o 'CoresPerSocket=[0-9]*'  | cut -d= -f2)
THREADS=$(echo "$HW" | grep -o 'ThreadsPerCore=[0-9]*'  | cut -d= -f2)
RAWMEM=$(echo "$HW"  | grep -o 'RealMemory=[0-9]*'      | cut -d= -f2)
# leave ~1% headroom so the node doesn't go DOWN on tiny mem accounting diffs
REALMEM=$(( RAWMEM * 99 / 100 ))
echo "node=$NODE cpus=$CPUS sockets=$SOCK cores=$CORES threads=$THREADS mem=${REALMEM}MB"

# GPUs -> gres
GPU_DEVS=$(ls /dev/nvidia[0-9]* 2>/dev/null | sort -V || true)
GPU_COUNT=$(echo "$GPU_DEVS" | grep -c . || true)
GRES_NODE="" ; GRES_TYPES=""
if [[ "$GPU_COUNT" -gt 0 ]]; then
  GRES_NODE="Gres=gpu:${GPU_COUNT}"
  GRES_TYPES="GresTypes=gpu"
  echo "GPUs detected: $GPU_COUNT"
fi

# cgroup v2 hosts: slurm 21.08 cgroup support is unreliable -> use linuxproc
CG=$(stat -fc %T /sys/fs/cgroup/ 2>/dev/null || echo unknown)
echo "cgroup: $CG (using proctrack/linuxproc + task/affinity)"

# ---- 4. directories ----
say "Creating spool/log directories"
$SUDO mkdir -p /var/spool/slurmctld /var/spool/slurmd /var/log/slurm
$SUDO chown slurm:slurm /var/spool/slurmctld /var/log/slurm
$SUDO chmod 755 /var/spool/slurmctld /var/spool/slurmd /var/log/slurm

# ---- 5. slurm.conf ----
say "Writing /etc/slurm/slurm.conf"
$SUDO mkdir -p /etc/slurm
$SUDO tee /etc/slurm/slurm.conf >/dev/null <<EOF
# slurm.conf - single-node cluster on ${NODE} (generated by setup-slurm skill)
ClusterName=${CLUSTER}
SlurmctldHost=${NODE}

AuthType=auth/munge
CryptoType=crypto/munge

SlurmctldPort=6817
SlurmdPort=6818
SlurmUser=slurm
SlurmdUser=root

StateSaveLocation=/var/spool/slurmctld
SlurmdSpoolDir=/var/spool/slurmd
SlurmctldPidFile=/run/slurmctld.pid
SlurmdPidFile=/run/slurmd.pid
SlurmctldLogFile=/var/log/slurm/slurmctld.log
SlurmdLogFile=/var/log/slurm/slurmd.log
SlurmctldDebug=info
SlurmdDebug=info

# cgroup v2 not reliably supported by slurm 21.08 -> track via linuxproc
ProctrackType=proctrack/linuxproc
TaskPlugin=task/affinity

SchedulerType=sched/backfill
SelectType=select/cons_tres
SelectTypeParameters=CR_Core_Memory

SlurmctldTimeout=120
SlurmdTimeout=300
InactiveLimit=0
MinJobAge=300
KillWait=30
Waittime=0
ReturnToService=2

# Email notifications: MailProg gets called as "mail -s <subject> <user>",
# body on stdin. /usr/bin/mail (bsd-mailx) pipes to /usr/sbin/sendmail -> msmtp.
MailProg=/usr/bin/mail

${GRES_TYPES}

JobAcctGatherType=jobacct_gather/linux
AccountingStorageType=accounting_storage/none

NodeName=${NODE} CPUs=${CPUS} Boards=1 SocketsPerBoard=${SOCK} CoresPerSocket=${CORES} ThreadsPerCore=${THREADS} RealMemory=${REALMEM} ${GRES_NODE} State=UNKNOWN
PartitionName=${PARTITION} Nodes=ALL Default=YES MaxTime=INFINITE State=UP
EOF
$SUDO chmod 644 /etc/slurm/slurm.conf

# gres.conf (only if GPUs)
if [[ "$GPU_COUNT" -gt 0 ]]; then
  say "Writing /etc/slurm/gres.conf"
  {
    echo "# gres.conf - GPU mapping (generated by setup-slurm skill)"
    for d in $GPU_DEVS; do echo "NodeName=${NODE} Name=gpu File=${d}"; done
  } | $SUDO tee /etc/slurm/gres.conf >/dev/null
  $SUDO chmod 644 /etc/slurm/gres.conf
fi

# ---- 6. msmtp (Gmail relay) ----
say "Writing /etc/msmtprc (Gmail SMTP relay)"
# NOTE: msmtp is AppArmor-confined; its logfile MUST be /var/log/msmtp
# (the profile allows /var/log/msmtp but NOT /var/log/msmtp.log).
$SUDO tee /etc/msmtprc >/dev/null <<EOF
defaults
auth           on
tls            on
tls_trust_file /etc/ssl/certs/ca-certificates.crt
logfile        /var/log/msmtp

account        relay
host           ${SMTP_HOST}
port           ${SMTP_PORT}
from           ${FROM_ADDR}
user           ${SMTP_USER}
password       ${APP_PW}

account default : relay
EOF
# slurmctld runs mail as the 'slurm' user, so the config must be readable by it.
$SUDO chown root:slurm /etc/msmtprc
$SUDO chmod 640 /etc/msmtprc
$SUDO touch /var/log/msmtp && $SUDO chmod 666 /var/log/msmtp

# ---- 7. start services ----
say "Starting slurmctld + slurmd"
$SUDO systemctl enable slurmctld slurmd >/dev/null 2>&1 || true
$SUDO systemctl restart slurmctld
$SUDO systemctl restart slurmd
sleep 2
systemctl is-active munge slurmctld slurmd

# bring the node online if it came up drained/down
scontrol update NodeName="${NODE}" State=RESUME 2>/dev/null || true
sleep 1
say "Cluster status"
sinfo

# ---- 8. mail self-test (as the slurm user = the real slurm path) ----
say "Sending a mail self-test as the 'slurm' user"
echo "setup-slurm mail self-test from $(hostname) at $(date)" \
  | ${SUDO:-sudo} -u slurm mail -s "[slurm] mail self-test on $(hostname -s)" "$EMAIL" \
  && echo "mail command exited 0"
sleep 2
echo "--- tail /var/log/msmtp ---"; $SUDO tail -3 /var/log/msmtp

# ---- 9. end-to-end test job ----
if [[ "$RUN_TEST" -eq 1 ]]; then
  say "Submitting a test job with --mail-type=BEGIN,END,FAIL"
  TMP=$(mktemp /tmp/slurm-mailtest.XXXX.sh)
  cat > "$TMP" <<EOF
#!/bin/bash
#SBATCH --job-name=mailtest
#SBATCH --partition=${PARTITION}
#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --mail-user=${EMAIL}
#SBATCH --output=/dev/null
sleep 5
echo done
EOF
  $SUDO truncate -s 0 /var/log/msmtp || true
  JID=$(sbatch --parsable "$TMP"); echo "submitted job $JID"
  for i in $(seq 1 20); do
    squeue -h -j "$JID" -o "%T" >/dev/null 2>&1 || break
    [[ -z "$(squeue -h -j "$JID" -o '%T' 2>/dev/null)" ]] && break
    sleep 2
  done
  sleep 2
  N=$($SUDO grep -c "smtpstatus=250" /var/log/msmtp || echo 0)
  echo "emails delivered for test job (expect 2 = BEGIN+END): $N"
  rm -f "$TMP"
fi

say "Done. Add these to any sbatch script for notifications:"
cat <<EOF
    #SBATCH --mail-type=BEGIN,END,FAIL     # or ALL
    #SBATCH --mail-user=${EMAIL}
$( [[ "$GPU_COUNT" -gt 0 ]] && echo "    #SBATCH --gres=gpu:1                    # request a GPU" )
EOF
